.section .text
# jmp_hell_200 jumps forth and back 200 times
# and returns timestamp counter after that
# uint64_t jmp_hell_200()
.global jmp_hell_200
jmp_hell_200:
	jmp jmp_hell_200_label_200
jmp_hell_200_label_1:
	jmp jmp_hell_200_label_199
jmp_hell_200_label_2:
	jmp jmp_hell_200_label_198
jmp_hell_200_label_3:
	jmp jmp_hell_200_label_197
jmp_hell_200_label_4:
	jmp jmp_hell_200_label_196
jmp_hell_200_label_5:
	jmp jmp_hell_200_label_195
jmp_hell_200_label_6:
	jmp jmp_hell_200_label_194
jmp_hell_200_label_7:
	jmp jmp_hell_200_label_193
jmp_hell_200_label_8:
	jmp jmp_hell_200_label_192
jmp_hell_200_label_9:
	jmp jmp_hell_200_label_191
jmp_hell_200_label_10:
	jmp jmp_hell_200_label_190
jmp_hell_200_label_11:
	jmp jmp_hell_200_label_189
jmp_hell_200_label_12:
	jmp jmp_hell_200_label_188
jmp_hell_200_label_13:
	jmp jmp_hell_200_label_187
jmp_hell_200_label_14:
	jmp jmp_hell_200_label_186
jmp_hell_200_label_15:
	jmp jmp_hell_200_label_185
jmp_hell_200_label_16:
	jmp jmp_hell_200_label_184
jmp_hell_200_label_17:
	jmp jmp_hell_200_label_183
jmp_hell_200_label_18:
	jmp jmp_hell_200_label_182
jmp_hell_200_label_19:
	jmp jmp_hell_200_label_181
jmp_hell_200_label_20:
	jmp jmp_hell_200_label_180
jmp_hell_200_label_21:
	jmp jmp_hell_200_label_179
jmp_hell_200_label_22:
	jmp jmp_hell_200_label_178
jmp_hell_200_label_23:
	jmp jmp_hell_200_label_177
jmp_hell_200_label_24:
	jmp jmp_hell_200_label_176
jmp_hell_200_label_25:
	jmp jmp_hell_200_label_175
jmp_hell_200_label_26:
	jmp jmp_hell_200_label_174
jmp_hell_200_label_27:
	jmp jmp_hell_200_label_173
jmp_hell_200_label_28:
	jmp jmp_hell_200_label_172
jmp_hell_200_label_29:
	jmp jmp_hell_200_label_171
jmp_hell_200_label_30:
	jmp jmp_hell_200_label_170
jmp_hell_200_label_31:
	jmp jmp_hell_200_label_169
jmp_hell_200_label_32:
	jmp jmp_hell_200_label_168
jmp_hell_200_label_33:
	jmp jmp_hell_200_label_167
jmp_hell_200_label_34:
	jmp jmp_hell_200_label_166
jmp_hell_200_label_35:
	jmp jmp_hell_200_label_165
jmp_hell_200_label_36:
	jmp jmp_hell_200_label_164
jmp_hell_200_label_37:
	jmp jmp_hell_200_label_163
jmp_hell_200_label_38:
	jmp jmp_hell_200_label_162
jmp_hell_200_label_39:
	jmp jmp_hell_200_label_161
jmp_hell_200_label_40:
	jmp jmp_hell_200_label_160
jmp_hell_200_label_41:
	jmp jmp_hell_200_label_159
jmp_hell_200_label_42:
	jmp jmp_hell_200_label_158
jmp_hell_200_label_43:
	jmp jmp_hell_200_label_157
jmp_hell_200_label_44:
	jmp jmp_hell_200_label_156
jmp_hell_200_label_45:
	jmp jmp_hell_200_label_155
jmp_hell_200_label_46:
	jmp jmp_hell_200_label_154
jmp_hell_200_label_47:
	jmp jmp_hell_200_label_153
jmp_hell_200_label_48:
	jmp jmp_hell_200_label_152
jmp_hell_200_label_49:
	jmp jmp_hell_200_label_151
jmp_hell_200_label_50:
	jmp jmp_hell_200_label_150
jmp_hell_200_label_51:
	jmp jmp_hell_200_label_149
jmp_hell_200_label_52:
	jmp jmp_hell_200_label_148
jmp_hell_200_label_53:
	jmp jmp_hell_200_label_147
jmp_hell_200_label_54:
	jmp jmp_hell_200_label_146
jmp_hell_200_label_55:
	jmp jmp_hell_200_label_145
jmp_hell_200_label_56:
	jmp jmp_hell_200_label_144
jmp_hell_200_label_57:
	jmp jmp_hell_200_label_143
jmp_hell_200_label_58:
	jmp jmp_hell_200_label_142
jmp_hell_200_label_59:
	jmp jmp_hell_200_label_141
jmp_hell_200_label_60:
	jmp jmp_hell_200_label_140
jmp_hell_200_label_61:
	jmp jmp_hell_200_label_139
jmp_hell_200_label_62:
	jmp jmp_hell_200_label_138
jmp_hell_200_label_63:
	jmp jmp_hell_200_label_137
jmp_hell_200_label_64:
	jmp jmp_hell_200_label_136
jmp_hell_200_label_65:
	jmp jmp_hell_200_label_135
jmp_hell_200_label_66:
	jmp jmp_hell_200_label_134
jmp_hell_200_label_67:
	jmp jmp_hell_200_label_133
jmp_hell_200_label_68:
	jmp jmp_hell_200_label_132
jmp_hell_200_label_69:
	jmp jmp_hell_200_label_131
jmp_hell_200_label_70:
	jmp jmp_hell_200_label_130
jmp_hell_200_label_71:
	jmp jmp_hell_200_label_129
jmp_hell_200_label_72:
	jmp jmp_hell_200_label_128
jmp_hell_200_label_73:
	jmp jmp_hell_200_label_127
jmp_hell_200_label_74:
	jmp jmp_hell_200_label_126
jmp_hell_200_label_75:
	jmp jmp_hell_200_label_125
jmp_hell_200_label_76:
	jmp jmp_hell_200_label_124
jmp_hell_200_label_77:
	jmp jmp_hell_200_label_123
jmp_hell_200_label_78:
	jmp jmp_hell_200_label_122
jmp_hell_200_label_79:
	jmp jmp_hell_200_label_121
jmp_hell_200_label_80:
	jmp jmp_hell_200_label_120
jmp_hell_200_label_81:
	jmp jmp_hell_200_label_119
jmp_hell_200_label_82:
	jmp jmp_hell_200_label_118
jmp_hell_200_label_83:
	jmp jmp_hell_200_label_117
jmp_hell_200_label_84:
	jmp jmp_hell_200_label_116
jmp_hell_200_label_85:
	jmp jmp_hell_200_label_115
jmp_hell_200_label_86:
	jmp jmp_hell_200_label_114
jmp_hell_200_label_87:
	jmp jmp_hell_200_label_113
jmp_hell_200_label_88:
	jmp jmp_hell_200_label_112
jmp_hell_200_label_89:
	jmp jmp_hell_200_label_111
jmp_hell_200_label_90:
	jmp jmp_hell_200_label_110
jmp_hell_200_label_91:
	jmp jmp_hell_200_label_109
jmp_hell_200_label_92:
	jmp jmp_hell_200_label_108
jmp_hell_200_label_93:
	jmp jmp_hell_200_label_107
jmp_hell_200_label_94:
	jmp jmp_hell_200_label_106
jmp_hell_200_label_95:
	jmp jmp_hell_200_label_105
jmp_hell_200_label_96:
	jmp jmp_hell_200_label_104
jmp_hell_200_label_97:
	jmp jmp_hell_200_label_103
jmp_hell_200_label_98:
	jmp jmp_hell_200_label_102
jmp_hell_200_label_99:
	jmp jmp_hell_200_label_101
jmp_hell_200_label_100:
	rdtsc
	shl $32, %rdx
	or %rdx, %rax
	ret
jmp_hell_200_label_101:
	jmp jmp_hell_200_label_100
jmp_hell_200_label_102:
	jmp jmp_hell_200_label_99
jmp_hell_200_label_103:
	jmp jmp_hell_200_label_98
jmp_hell_200_label_104:
	jmp jmp_hell_200_label_97
jmp_hell_200_label_105:
	jmp jmp_hell_200_label_96
jmp_hell_200_label_106:
	jmp jmp_hell_200_label_95
jmp_hell_200_label_107:
	jmp jmp_hell_200_label_94
jmp_hell_200_label_108:
	jmp jmp_hell_200_label_93
jmp_hell_200_label_109:
	jmp jmp_hell_200_label_92
jmp_hell_200_label_110:
	jmp jmp_hell_200_label_91
jmp_hell_200_label_111:
	jmp jmp_hell_200_label_90
jmp_hell_200_label_112:
	jmp jmp_hell_200_label_89
jmp_hell_200_label_113:
	jmp jmp_hell_200_label_88
jmp_hell_200_label_114:
	jmp jmp_hell_200_label_87
jmp_hell_200_label_115:
	jmp jmp_hell_200_label_86
jmp_hell_200_label_116:
	jmp jmp_hell_200_label_85
jmp_hell_200_label_117:
	jmp jmp_hell_200_label_84
jmp_hell_200_label_118:
	jmp jmp_hell_200_label_83
jmp_hell_200_label_119:
	jmp jmp_hell_200_label_82
jmp_hell_200_label_120:
	jmp jmp_hell_200_label_81
jmp_hell_200_label_121:
	jmp jmp_hell_200_label_80
jmp_hell_200_label_122:
	jmp jmp_hell_200_label_79
jmp_hell_200_label_123:
	jmp jmp_hell_200_label_78
jmp_hell_200_label_124:
	jmp jmp_hell_200_label_77
jmp_hell_200_label_125:
	jmp jmp_hell_200_label_76
jmp_hell_200_label_126:
	jmp jmp_hell_200_label_75
jmp_hell_200_label_127:
	jmp jmp_hell_200_label_74
jmp_hell_200_label_128:
	jmp jmp_hell_200_label_73
jmp_hell_200_label_129:
	jmp jmp_hell_200_label_72
jmp_hell_200_label_130:
	jmp jmp_hell_200_label_71
jmp_hell_200_label_131:
	jmp jmp_hell_200_label_70
jmp_hell_200_label_132:
	jmp jmp_hell_200_label_69
jmp_hell_200_label_133:
	jmp jmp_hell_200_label_68
jmp_hell_200_label_134:
	jmp jmp_hell_200_label_67
jmp_hell_200_label_135:
	jmp jmp_hell_200_label_66
jmp_hell_200_label_136:
	jmp jmp_hell_200_label_65
jmp_hell_200_label_137:
	jmp jmp_hell_200_label_64
jmp_hell_200_label_138:
	jmp jmp_hell_200_label_63
jmp_hell_200_label_139:
	jmp jmp_hell_200_label_62
jmp_hell_200_label_140:
	jmp jmp_hell_200_label_61
jmp_hell_200_label_141:
	jmp jmp_hell_200_label_60
jmp_hell_200_label_142:
	jmp jmp_hell_200_label_59
jmp_hell_200_label_143:
	jmp jmp_hell_200_label_58
jmp_hell_200_label_144:
	jmp jmp_hell_200_label_57
jmp_hell_200_label_145:
	jmp jmp_hell_200_label_56
jmp_hell_200_label_146:
	jmp jmp_hell_200_label_55
jmp_hell_200_label_147:
	jmp jmp_hell_200_label_54
jmp_hell_200_label_148:
	jmp jmp_hell_200_label_53
jmp_hell_200_label_149:
	jmp jmp_hell_200_label_52
jmp_hell_200_label_150:
	jmp jmp_hell_200_label_51
jmp_hell_200_label_151:
	jmp jmp_hell_200_label_50
jmp_hell_200_label_152:
	jmp jmp_hell_200_label_49
jmp_hell_200_label_153:
	jmp jmp_hell_200_label_48
jmp_hell_200_label_154:
	jmp jmp_hell_200_label_47
jmp_hell_200_label_155:
	jmp jmp_hell_200_label_46
jmp_hell_200_label_156:
	jmp jmp_hell_200_label_45
jmp_hell_200_label_157:
	jmp jmp_hell_200_label_44
jmp_hell_200_label_158:
	jmp jmp_hell_200_label_43
jmp_hell_200_label_159:
	jmp jmp_hell_200_label_42
jmp_hell_200_label_160:
	jmp jmp_hell_200_label_41
jmp_hell_200_label_161:
	jmp jmp_hell_200_label_40
jmp_hell_200_label_162:
	jmp jmp_hell_200_label_39
jmp_hell_200_label_163:
	jmp jmp_hell_200_label_38
jmp_hell_200_label_164:
	jmp jmp_hell_200_label_37
jmp_hell_200_label_165:
	jmp jmp_hell_200_label_36
jmp_hell_200_label_166:
	jmp jmp_hell_200_label_35
jmp_hell_200_label_167:
	jmp jmp_hell_200_label_34
jmp_hell_200_label_168:
	jmp jmp_hell_200_label_33
jmp_hell_200_label_169:
	jmp jmp_hell_200_label_32
jmp_hell_200_label_170:
	jmp jmp_hell_200_label_31
jmp_hell_200_label_171:
	jmp jmp_hell_200_label_30
jmp_hell_200_label_172:
	jmp jmp_hell_200_label_29
jmp_hell_200_label_173:
	jmp jmp_hell_200_label_28
jmp_hell_200_label_174:
	jmp jmp_hell_200_label_27
jmp_hell_200_label_175:
	jmp jmp_hell_200_label_26
jmp_hell_200_label_176:
	jmp jmp_hell_200_label_25
jmp_hell_200_label_177:
	jmp jmp_hell_200_label_24
jmp_hell_200_label_178:
	jmp jmp_hell_200_label_23
jmp_hell_200_label_179:
	jmp jmp_hell_200_label_22
jmp_hell_200_label_180:
	jmp jmp_hell_200_label_21
jmp_hell_200_label_181:
	jmp jmp_hell_200_label_20
jmp_hell_200_label_182:
	jmp jmp_hell_200_label_19
jmp_hell_200_label_183:
	jmp jmp_hell_200_label_18
jmp_hell_200_label_184:
	jmp jmp_hell_200_label_17
jmp_hell_200_label_185:
	jmp jmp_hell_200_label_16
jmp_hell_200_label_186:
	jmp jmp_hell_200_label_15
jmp_hell_200_label_187:
	jmp jmp_hell_200_label_14
jmp_hell_200_label_188:
	jmp jmp_hell_200_label_13
jmp_hell_200_label_189:
	jmp jmp_hell_200_label_12
jmp_hell_200_label_190:
	jmp jmp_hell_200_label_11
jmp_hell_200_label_191:
	jmp jmp_hell_200_label_10
jmp_hell_200_label_192:
	jmp jmp_hell_200_label_9
jmp_hell_200_label_193:
	jmp jmp_hell_200_label_8
jmp_hell_200_label_194:
	jmp jmp_hell_200_label_7
jmp_hell_200_label_195:
	jmp jmp_hell_200_label_6
jmp_hell_200_label_196:
	jmp jmp_hell_200_label_5
jmp_hell_200_label_197:
	jmp jmp_hell_200_label_4
jmp_hell_200_label_198:
	jmp jmp_hell_200_label_3
jmp_hell_200_label_199:
	jmp jmp_hell_200_label_2
jmp_hell_200_label_200:
	jmp jmp_hell_200_label_1
